//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.ProductionMaterials = new HashSet<ProductionMaterial>();
        }
    
        public int MeterialId { get; set; }
        public string Name { get; set; }
        public string Descripion { get; set; }
        public Nullable<decimal> PricePerKilo { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual ICollection<ProductionMaterial> ProductionMaterials { get; set; }
    }
}
