//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
            this.Productions = new HashSet<Production>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> Wieght { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ICollection<Production> Productions { get; set; }
    }
}
