//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionMaterial
    {
        public int ProductionMaterialId { get; set; }
        public int FK_ProductionId { get; set; }
        public int FK_MaterialId { get; set; }
        public double Percentage { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Production Production { get; set; }
    }
}
