//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopSeller.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IShop")]
    public interface IShop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetData", ReplyAction="http://tempuri.org/IShop/GetDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IShop/GetDataUsingDataContractResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ShopSeller.ServiceReference2.CompositeType GetDataUsingDataContract(ShopSeller.ServiceReference2.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/AddEmploye", ReplyAction="http://tempuri.org/IShop/AddEmployeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddEmploye(string Name, string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/AddStock", ReplyAction="http://tempuri.org/IShop/AddStockResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddStock(string Name, string Address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/AddItem", ReplyAction="http://tempuri.org/IShop/AddItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddItem(string Name, string price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/FillEmployes", ReplyAction="http://tempuri.org/IShop/FillEmployesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable FillEmployes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/FillStocks", ReplyAction="http://tempuri.org/IShop/FillStocksResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable FillStocks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/FillItems", ReplyAction="http://tempuri.org/IShop/FillItemsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable FillItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/CreateInvoiceCode", ReplyAction="http://tempuri.org/IShop/CreateInvoiceCodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateInvoiceCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/InsertInvoiceData", ReplyAction="http://tempuri.org/IShop/InsertInvoiceDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertInvoiceData(string xml, string Date, int EmployeNAme, int stockName, int tax, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/FillInvoices", ReplyAction="http://tempuri.org/IShop/FillInvoicesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable FillInvoices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetInvoiceData", ReplyAction="http://tempuri.org/IShop/GetInvoiceDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetInvoiceData(int Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetAllEmployesData", ReplyAction="http://tempuri.org/IShop/GetAllEmployesDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllEmployesData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetAllItemsData", ReplyAction="http://tempuri.org/IShop/GetAllItemsDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllItemsData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetAllStockssData", ReplyAction="http://tempuri.org/IShop/GetAllStockssDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllStockssData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/UpdateEmploye", ReplyAction="http://tempuri.org/IShop/UpdateEmployeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateEmploye(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/UpdateStock", ReplyAction="http://tempuri.org/IShop/UpdateStockResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateStock(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/UpdateEItem", ReplyAction="http://tempuri.org/IShop/UpdateEItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateEItem(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/UpdateInvoiceXML", ReplyAction="http://tempuri.org/IShop/UpdateInvoiceXMLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateInvoiceXML(string xml, string Date, int EmployeNAme, int stockName, int tax, string Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/DeleteEmployee", ReplyAction="http://tempuri.org/IShop/DeleteEmployeeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteEmployee(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/DeleteItem", ReplyAction="http://tempuri.org/IShop/DeleteItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteItem(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/DeleteStock", ReplyAction="http://tempuri.org/IShop/DeleteStockResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteStock(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/DeleteInvoice", ReplyAction="http://tempuri.org/IShop/DeleteInvoiceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DeleteInvoice(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetDBTables", ReplyAction="http://tempuri.org/IShop/GetDBTablesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDBTables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/GetDBTableColumns", ReplyAction="http://tempuri.org/IShop/GetDBTableColumnsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDBTableColumns(string tblName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/EmployeeSelect", ReplyAction="http://tempuri.org/IShop/EmployeeSelectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable EmployeeSelect(string name, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShop/ExecuteCommand", ReplyAction="http://tempuri.org/IShop/ExecuteCommandResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ExecuteCommand(string command);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompositeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool boolValueField;
        
        private string stringValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
                this.RaisePropertyChanged("BoolValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
                this.RaisePropertyChanged("StringValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopChannel : ShopSeller.ServiceReference2.IShop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopClient : System.ServiceModel.ClientBase<ShopSeller.ServiceReference2.IShop>, ShopSeller.ServiceReference2.IShop {
        
        public ShopClient() {
        }
        
        public ShopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public ShopSeller.ServiceReference2.CompositeType GetDataUsingDataContract(ShopSeller.ServiceReference2.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public string AddEmploye(string Name, string Address) {
            return base.Channel.AddEmploye(Name, Address);
        }
        
        public string AddStock(string Name, string Address) {
            return base.Channel.AddStock(Name, Address);
        }
        
        public string AddItem(string Name, string price) {
            return base.Channel.AddItem(Name, price);
        }
        
        public System.Data.DataTable FillEmployes() {
            return base.Channel.FillEmployes();
        }
        
        public System.Data.DataTable FillStocks() {
            return base.Channel.FillStocks();
        }
        
        public System.Data.DataTable FillItems() {
            return base.Channel.FillItems();
        }
        
        public string CreateInvoiceCode() {
            return base.Channel.CreateInvoiceCode();
        }
        
        public string InsertInvoiceData(string xml, string Date, int EmployeNAme, int stockName, int tax, string Code) {
            return base.Channel.InsertInvoiceData(xml, Date, EmployeNAme, stockName, tax, Code);
        }
        
        public System.Data.DataTable FillInvoices() {
            return base.Channel.FillInvoices();
        }
        
        public System.Data.DataTable GetInvoiceData(int Code) {
            return base.Channel.GetInvoiceData(Code);
        }
        
        public System.Data.DataTable GetAllEmployesData() {
            return base.Channel.GetAllEmployesData();
        }
        
        public System.Data.DataTable GetAllItemsData() {
            return base.Channel.GetAllItemsData();
        }
        
        public System.Data.DataTable GetAllStockssData() {
            return base.Channel.GetAllStockssData();
        }
        
        public string UpdateEmploye(string xml) {
            return base.Channel.UpdateEmploye(xml);
        }
        
        public string UpdateStock(string xml) {
            return base.Channel.UpdateStock(xml);
        }
        
        public string UpdateEItem(string xml) {
            return base.Channel.UpdateEItem(xml);
        }
        
        public string UpdateInvoiceXML(string xml, string Date, int EmployeNAme, int stockName, int tax, string Code) {
            return base.Channel.UpdateInvoiceXML(xml, Date, EmployeNAme, stockName, tax, Code);
        }
        
        public string DeleteEmployee(int ID) {
            return base.Channel.DeleteEmployee(ID);
        }
        
        public string DeleteItem(int ID) {
            return base.Channel.DeleteItem(ID);
        }
        
        public string DeleteStock(int ID) {
            return base.Channel.DeleteStock(ID);
        }
        
        public string DeleteInvoice(int ID) {
            return base.Channel.DeleteInvoice(ID);
        }
        
        public System.Data.DataTable GetDBTables() {
            return base.Channel.GetDBTables();
        }
        
        public System.Data.DataTable GetDBTableColumns(string tblName) {
            return base.Channel.GetDBTableColumns(tblName);
        }
        
        public System.Data.DataTable EmployeeSelect(string name, string address) {
            return base.Channel.EmployeeSelect(name, address);
        }
        
        public System.Data.DataTable ExecuteCommand(string command) {
            return base.Channel.ExecuteCommand(command);
        }
    }
}
